apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-secret
  labels:
    app: home
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: home-secret
    creationPolicy: Owner
  data:
    - secretKey: MAILERLITE_API_TOKEN
      remoteRef:
        key: mailerlite-api-token
