apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: home
  labels:
    app: home
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external
      namespace: platform
  hostnames:
    - home.dev.konnektr.io
    # - konnektr.io
    # - www.konnektr.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: home
          port: 8080
