apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # CRDs must be installed before issuers
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: platform
  source:
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
        featureGates: GatewayAPISupport
        nodeSelector:
          cloud.google.com/gke-spot: "true"
        terminationGracePeriodSeconds: 25
        webhook:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
          terminationGracePeriodSeconds: 25
        cainjector:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
          terminationGracePeriodSeconds: 25
        startupapicheck:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
          terminationGracePeriodSeconds: 25
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.1
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[0].namespaceSelector.matchExpressions[] | select(.key=="kubernetes.azure.com/managedby")
        - .webhooks[0].namespaceSelector.matchExpressions[] | select(.key=="control-plane")
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
