apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: docs
  labels:
    app: docs
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external
      namespace: platform
  hostnames:
    - docs.dev.konnektr.io
    # - docs.konnektr.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: docs
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: docs-home
  labels:
    app: docs
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external
      namespace: platform
  hostnames:
    - home.dev.konnektr.io
    # - konnektr.io
    # - www.konnektr.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /docs
      backendRefs:
        - name: docs
          port: 8080
