apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - default-approject.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.9/manifests/install.yaml
  - platform-app.yaml
  - argocd-server-httproute.yaml
  - auth0-external-secret.yaml
  # - github-webhook-external-secret.yaml
  - argocd-application-rbac.yaml
  - argocd-server-application-controller-rbac.yaml

patches:
  - path: argocd-cm.yaml
  - path: argocd-cmd-params-cm.yaml
  - path: remove-dex.yaml
    target:
      labelSelector: "app.kubernetes.io/component=dex-server"
  - path: remove-dex.yaml
    target:
      name: argocd-dex-server-network-policy
      kind: NetworkPolicy
  # - path: argocd-prometheus.yaml
  - path: enable-exec.yaml
  - path: enable-exec-json6902.yaml
    target:
      kind: Role
      name: argocd-server
  - path: enable-exec-json6902.yaml
    target:
      kind: ClusterRole
      name: argocd-server
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: .*
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector/cloud.google.com~1gke-spot
        value: 'true'
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: cloud.google.com/gke-spot
            operator: Equal
            value: 'true'
            effect: NoSchedule
      - op: add
        path: /spec/template/spec/terminationGracePeriodSeconds
        value: 25
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: .*
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector/cloud.google.com~1gke-spot
        value: 'true'
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: cloud.google.com/gke-spot
            operator: Equal
            value: 'true'
            effect: NoSchedule
      - op: add
        path: /spec/template/spec/terminationGracePeriodSeconds
        value: 25