apiVersion: kubernetes.auth0.com/v1
kind: Tenant
metadata:
  name: konnektr-tenant
  namespace: ktrlplane
spec:
  auth:
    domain: dev-zv5urb33g0msy7bc.eu.auth0.com
    secretRef:
      name: auth0-operator-credentials
  conf:
    friendly_name: Konnektr Tenant
  name: konnektr-tenant
