apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - httproute.yaml
  - stripe-external-secret.yaml
  - namespace-dbqr.yaml
  - auth0-client-dbqr.yaml

helmCharts:
  - name: ktrlplane
    releaseName: ktrlplane
    valuesFile: values.yaml
    repo: https://charts.konnektr.io
    version: 0.3.24
    namespace: ktrlplane
