apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stripe-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: stripe-secret
    creationPolicy: Owner
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: stripe-secret-key
    - secretKey: STRIPE_PUBLISHABLE_KEY
      remoteRef:
        key: stripe-publishable-key
