# Spot node configuration
nodeSelector:
  cloud.google.com/gke-spot: "true"
terminationGracePeriodSeconds: 15

database:
  enabled: false
  useExternalSecret: true
  externalSecretName: "ktrlplane-app"
  secretKeys:
    host: host
    port: port
    db: dbname
    user: user
    password: password

httproute:
  enabled: true

frontend:
  nodeSelector:
    cloud.google.com/gke-spot: "true"
    
backend:
  nodeSelector:
    cloud.google.com/gke-spot: "true"
  
stripe:
  enabled: true
  useExternalSecret: true
  externalSecretName: "stripe-secret"
  # Product configuration (safe to store in values)
  products:
    - resource_type: "Konnektr.Graph"
      sku: "free"
      product_id: "prod_TZgQnSI63Z4aKc"
    - resource_type: "Konnektr.Graph"
      sku: "standard"
      product_id: "prod_TTFdx010Hv2Qg4"

db-query-operator:
  enabled: false