apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clientgrants.kubernetes.auth0.com
spec:
  group: kubernetes.auth0.com
  names:
    kind: ClientGrant
    listKind: ClientGrantList
    plural: clientgrants
    singular: clientgrant
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenantRef:
                  type: object
                  properties:
                    name:
                      type: string
                conf:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
