apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/tenants_kubernetes_auth0_com.yaml
  - crds/resourceservers_kubernetes_auth0_com.yaml
  - crds/clients_kubernetes_auth0_com.yaml
  - crds/clientgrants_kubernetes_auth0_com.yaml
  - auth0-operator-app.yaml
  - auth0-operator-external-secret.yaml
  - auth0-tenant.yaml
