apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: graph-explorer-frontend
spec:
  parentRefs:
    - name: external
      namespace: platform
  hostnames:
    - explorer.graph.konnektr.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/
      backendRefs:
        - name: graph-explorer-backend
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: graph-explorer-frontend
          port: 80
