apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appproject.yaml
  - graph-dbqr.yaml
  - graph-explorer-frontend.yaml
  - graph-explorer-backend.yaml
  - graph-explorer-httproute.yaml
