apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: graph
    releaseName: graph
    valuesFile: values.yaml
    repo: https://charts.konnektr.io
    version: 0.4.14
    namespace: graph
