apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-httproute.yaml
  - n8n-external-secret.yaml
  - n8n-cluster.yaml
  - n8n-pvc.yaml
