apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n
spec:
  parentRefs:
    - name: external
      namespace: platform
      sectionName: n8n-https
  hostnames:
    - n8n.konnektr.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: n8n
          port: 5678
