apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - graph-mcp-deployment.yaml
  - graph-mcp-service.yaml
  - graph-mcp-httproute.yaml
  - auth0-external-secret.yaml
  - graph-mcp-oauth-pvc.yaml
  - mcp-vertexai-external-secret.yaml
