apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-vertexai
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: mcp-vertexai
    creationPolicy: Owner
  data:
    - secretKey: apikey
      remoteRef:
        key: mcp-vertexai-apikey
