apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth0-operator-credentials
  namespace: platform
spec:
  secretStoreRef:
    name: external-secrets-cluster-store
    kind: ClusterSecretStore
  target:
    name: auth0-operator-credentials
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: auth0-operator-client-id
    - secretKey: clientSecret
      remoteRef:
        key: auth0-operator-client-secret
