apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth0-operator-external-secret.yaml

helmCharts:
  - name: auth0-operator
    releaseName: auth0-operator
    valuesFile: values.yaml
    repo: https://github.com/alethic/auth0-operator//charts/auth0-operator?ref=1.3.4
    version: 1.3.4
    namespace: auth0-operator
