apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth0-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: auth0-operator
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: https://github.com/alethic/auth0-operator.git
    targetRevision: 1.3.4
    path: charts/auth0-operator
    helm:
      valuesObject:
        operator:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
