apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-porkbun-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3" # After cert-manager is ready
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: https://charts.konnektr.io
    targetRevision: "0.1.5"
    chart: porkbun-webhook
    helm:
      valuesObject:
        nodeSelector:
          cloud.google.com/gke-spot: "true"
        resources: 
          requests:
            memory: "300Mi"
            cpu: "5m"
          limits:
            memory: "600Mi"
            cpu: "100m"
        terminationGracePeriodSeconds: 15
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
