apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # CRDs must be installed before issuers
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: v1.19.1
    chart: cert-manager
    path: .
    helm:
      valuesObject:
        crds:
          enabled: true
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
          enableGatewayAPI: true
        nodeSelector:
          cloud.google.com/gke-spot: "true"
        webhook:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
        cainjector:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
        startupapicheck:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
        leaderElection:
          namespace: cert-manager
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[0].namespaceSelector.matchExpressions[] | select(.key=="kubernetes.azure.com/managedby")
        - .webhooks[0].namespaceSelector.matchExpressions[] | select(.key=="control-plane")
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
