apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbqo-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dbqo-system
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: oci://ghcr.io/konnektr-io/charts/db-query-operator
    targetRevision: 0.9.0
    path: .
    helm:
      valuesObject:
        gvkPattern: "argoproj.io/v1alpha1/Application;argoproj.io/v1alpha1/AppProject;v1/Namespace;networking.k8s.io/v1/NetworkPolicy;kubernetes.auth0.com/v1/Client;kubernetes.auth0.com/v1/ClientGrant"
        logLevel: error
        nodeSelector:
          cloud.google.com/gke-spot: "true"
        resources: 
          requests:
            memory: "300Mi"
            cpu: "50m"
          limits:
            memory: "600Mi"
            cpu: "100m"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
