apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbqo-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dbqo-system
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: oci://ghcr.io/konnektr-io/charts/db-query-operator
    targetRevision: 0.6.7
    path: .
    helm:
      valuesObject:
        gvkPattern: "argoproj.io/v1alpha1/Application;argoproj.io/v1alpha1/AppProject;v1/Namespace"
        nodeSelector:
          cloud.google.com/gke-spot: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
