apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-system
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    path: .
    targetRevision: 1.x
    helm:
      valuesObject:
        deployment:
          pod:
            nodeSelector:
              cloud.google.com/gke-spot: "true"
        extProc:
          extraEnvVars:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.opentelemetry.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SERVICE_NAME
              value: envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external-http-proxy
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
          terminationGracePeriodSeconds: 25
