apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: platform
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      hostname: argocd.konnektr.io
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-tls
    - name: https
      protocol: HTTPS
      port: 443
      hostname: oauth.konnektr.io
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: oauth-tls
    - name: https
      protocol: HTTPS
      port: 443
      hostname: ktrlplane.konnektr.io
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: ktrlplane-tls
