apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: platform
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    - name: docs-https
      protocol: HTTPS
      port: 443
      hostname: "docs.konnektr.io"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: docs-tls
    - name: dev-https
      protocol: HTTPS
      hostname: "*.dev.konnektr.io"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: dev-tls
    - name: argocd-https
      protocol: HTTPS
      hostname: argocd.konnektr.io
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: argocd-tls
    - name: oauth-https
      protocol: HTTPS
      port: 443
      hostname: oauth.konnektr.io
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: oauth-tls
    - name: ktrlplane-https
      protocol: HTTPS
      port: 443
      hostname: ktrlplane.konnektr.io
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: ktrlplane-tls
    - name: graph-api-https
      protocol: HTTPS
      port: 443
      hostname: "*.api.graph.konnektr.io"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: graph-api-tls
    - name: graph-https
      protocol: HTTPS
      port: 443
      hostname: "*.graph.konnektr.io"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: graph-tls
    - name: n8n-https
      protocol: HTTPS
      port: 443
      hostname: "n8n.konnektr.io"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: n8n-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect
  namespace: platform
spec:
  parentRefs:
  - name: external
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: 443