apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets-app.yaml
  - external-secrets-cluster-store.yaml

  - argocd-app.yaml

  - cert-manager-app.yaml
  - cert-manager-porkbun-webhook-app.yaml
  - cert-issuers.yaml
  - postgres-gateway-certificate.yaml

  - envoy-gateway-system-app.yaml
  - external-gateway-envoyproxy.yaml
  - external-gateway.yaml
  
  - dbqo-system-app.yaml
  - platform-appset.yaml
  - apps-appproject.yaml
  - apps-appset.yaml


  # - oauth-gateway.yaml
  # - global-auth0-security-policy.yaml

  # - loki.yaml
  # - mimir.yaml
  # - prometheus.yaml
  # - opentelemetry-collector.yaml