apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-distributed
    targetRevision: 0.77.2
    helm:
      valuesObject:
        loki:
          auth_enabled: true
          tenant_mode: org-id
          storage:
            type: gcs
            gcs:
              bucketName: "konnektr-loki-data"
              serviceAccount:
                secretKeyRef:
                  name: gcs-credentials
                  key: gcs.json
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
