apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-gateway-tls
  namespace: platform
spec:
  secretName: postgres-gateway-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.db.konnektr.io"
