apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceservers.kubernetes.auth0.com
spec:
  group: kubernetes.auth0.com
  names:
    kind: ResourceServer
    listKind: ResourceServerList
    plural: resourceservers
    singular: resourceserver
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenantRef:
                  type: object
                  properties:
                    name:
                      type: string
                conf:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
